username: "your_username"
password: "your_password"
cf_token: "your_token"
jira_server: "your_jira_url"
project: "YOUR_PROJECT"
confluence_server: "your_confluence_url"
sf_username: "saleforce_username"
sf_password: "saleforce_password"
sf_security_token: "saleforce_token"